import 'package:example/person.dart';

final List<Person> mockData = [
  Person(firstName: 'John', lastName: 'Doe', age: 28),
  Person(firstName: 'Jane', lastName: 'Smith', age: 34),
  Person(firstName: 'Alice', lastName: 'Johnson', age: 22),
  Person(firstName: 'Bob', lastName: 'Brown', age: 45),
  Person(firstName: 'Emily', lastName: 'Davis', age: 31),
  Person(firstName: 'Michael', lastName: 'Miller', age: 40),
  Person(firstName: 'Sarah', lastName: 'Wilson', age: 27),
  Person(firstName: 'David', lastName: 'Moore', age: 52),
  Person(firstName: 'Laura', lastName: 'Taylor', age: 38),
  Person(firstName: 'James', lastName: 'Anderson', age: 29),
  Person(firstName: 'Oliver', lastName: 'Thomas', age: 36),
  Person(firstName: 'Sophia', lastName: 'Martinez', age: 24),
  Person(firstName: 'Liam', lastName: 'Harris', age: 33),
  Person(firstName: 'Mia', lastName: 'Clark', age: 29),
  Person(firstName: 'Noah', lastName: 'Lewis', age: 41),
  Person(firstName: 'Isabella', lastName: 'Robinson', age: 26),
  Person(firstName: 'William', lastName: 'Walker', age: 50),
  Person(firstName: 'Amelia', lastName: 'Hall', age: 37),
  Person(firstName: 'Elijah', lastName: 'Allen', age: 30),
  Person(firstName: 'Charlotte', lastName: 'Young', age: 35),
  Person(firstName: 'Ethan', lastName: 'King', age: 32),
  Person(firstName: 'Ava', lastName: 'Wright', age: 28),
  Person(firstName: 'Benjamin', lastName: 'Scott', age: 45),
  Person(firstName: 'Harper', lastName: 'Green', age: 22),
  Person(firstName: 'Alexander', lastName: 'Baker', age: 39),
  Person(firstName: 'Evelyn', lastName: 'Adams', age: 27),
  Person(firstName: 'Sebastian', lastName: 'Nelson', age: 34),
  Person(firstName: 'Grace', lastName: 'Carter', age: 31),
  Person(firstName: 'Lucas', lastName: 'Mitchell', age: 46),
  Person(firstName: 'Zoe', lastName: 'Perez', age: 24),
];
